Added Gmail client
W6-Assess/dev pull request #18
Opened 2016-09-21 16:50 UTC by howareyouman

2016-10-09 23:02 UTC, raymon-02 commented on src/main/java/com/w6/controller/EndpointController.java
> +    protected static final String EMAILS_VIEW = "emails";
Why protected not private?

2016-10-09 23:02 UTC, raymon-02 commented on src/main/java/com/w6/controller/EndpointController.java
> +            {
Not java convention style with brackets

2016-10-09 23:02 UTC, raymon-02 commented on src/main/java/com/w6/controller/EndpointController.java
> +            if (emailId != null)
Should be under try block

2016-10-09 23:02 UTC, raymon-02 commented on src/main/java/com/w6/data/Email.java
> +    public long id;
Public fields are bad solution

2016-10-09 23:02 UTC, raymon-02 commented on src/main/java/com/w6/email/GmailClient.java
> +    private Session session = null;
It's already null

2016-10-09 23:02 UTC, raymon-02 commented on src/main/java/com/w6/email/GmailClient.java
> +        folder.close(false);
If folder is null?
So further

2016-10-12 16:17 UTC, howareyouman commented on src/main/java/com/w6/controller/EndpointController.java
> +    protected static final String EMAILS_VIEW = "emails";
I wonder that it could be changed from another place.

2016-10-12 16:19 UTC, howareyouman commented on src/main/java/com/w6/data/Email.java
> +    public long id;
We use public fields to use Gson

2016-10-12 16:34 UTC, howareyouman commented on src/main/java/com/w6/controller/EndpointController.java
> +            {
Mikhail use this style =) He advised me to use this style. I don't like it as well

2016-10-12 20:54 UTC, raymon-02 commented
+

2016-10-15 17:29 UTC, towelenee commented on src/main/java/com/w6/controller/EndpointController.java
> +    protected static final String EMAILS_VIEW = "emails";
It should be private, if you are not garantee that this field is working fine with inheretance, you should use private.

2016-10-15 17:29 UTC, towelenee commented on src/main/java/com/w6/data/Email.java
> +    public long id;
Gson can serialize private fields.

2016-10-15 17:35 UTC, towelenee requested changes

2016-10-15 17:35 UTC, towelenee commented on src/main/java/com/w6/controller/EndpointController.java
> +    public ModelAndView displayInput(@RequestParam(value = "emailid", required = false) Long emailId) throws IOException
email_id

2016-10-15 17:35 UTC, towelenee commented on src/main/java/com/w6/email/GmailClient.java
> +    public void connect() throws Exception {
It should not be public. Class should have simple interfaces, all rest should be private

2016-10-15 17:35 UTC, towelenee commented on src/main/java/com/w6/email/GmailClient.java
> +    public Collection<Message> getUnreadMessages() throws MessagingException {
This should be only public method

2016-10-15 17:35 UTC, towelenee commented on src/main/java/com/w6/email/GmailClient.java
> +    public void printMessage(int messageNo) throws Exception {
Debug function?

2016-10-18 12:13 UTC, raymon-02 commented
+1

2016-10-18 12:36 UTC, towelenee commented
Could you please explain in details, how do you store password?

El 18 oct. 2016 14:13, "Ilia" <notifications@github.com> escribió:

> +1
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/W6-Assess/dev/pull/18#issuecomment-254489279>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/ADpU6j82Zwy48__jIlAnyH_28KogAvpIks5q1Lf8gaJpZM4KDCPj>
> .
>

2016-10-31 19:43 UTC, merged