Refactoring of 'map' branch with map and relevancy list
W6-Assess/dev pull request #25
Opened 2016-11-09 15:04 UTC by raymon-02

2016-11-16 10:04 UTC, howareyouman commented
+

2016-11-22 20:39 UTC, towelenee requested changes

2016-11-22 20:39 UTC, towelenee commented on src/main/java/com/w6/controller/EndpointController.java
> +    private static final Logger LOGGER = Logger.getLogger(EndpointController.class.getName());
Logger.
Why not beans? Logger should be same for every class

2016-11-22 20:39 UTC, towelenee commented on src/main/webapp/WEB-INF/templates/index.html
> +                                                "event_description": "2 MDM aid workers are abducted by Somali gunmen",
Why here is some data?

2017-02-11 14:11 UTC, merged